#include "CppGenerator.h"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <cmath>

static void ensureParentDirectory(const std::filesystem::path& path) {
    std::filesystem::create_directories(path.parent_path());
}


static std::string cppFloat(float value) {
    if (!std::isfinite(value)) return "0.0f";

    std::ostringstream out;
    out << std::setprecision(9) << value;
    std::string literal = out.str();
    if (literal.find_first_of(".eE") == std::string::npos) literal += ".0";
    literal += "f";
    return literal;
}

static std::string escapeCpp(const std::string& s) {
    std::string out;
    for (char c : s) {
        if (c == '\\') out += "\\\\";
        else if (c == '"') out += "\\\"";
        else if (c == '\n') out += "\\n";
        else if (c == '\r') out += "\\r";
        else if (c == '\t') out += "\\t";
        else out += c;
    }
    return out;
}

bool CppGenerator::writeRegistries(const std::filesystem::path& outputPath, const std::vector<EditorObject>& objects) {
    ensureParentDirectory(outputPath);
    std::ofstream out(outputPath);
    if (!out) return false;

    out << "// AUTO-GENERATED BY AXEditor.\n";
    out << "// Source of truth: .axscene / .axentity / .axcombo / .axmat files.\n";
    out << "// Do not place hand-written gameplay here; use scripts/*.cpp for user code.\n\n";
    out << "#include <string>\n";
    out << "#include <vector>\n\n";
    out << "struct AXGeneratedProperty { const char* name; const char* value; };\n";
    out << "struct AXGeneratedComponent {\n";
    out << "    const char* type;\n";
    out << "    bool active;\n";
    out << "    bool dynamic;\n";
    out << "    std::vector<AXGeneratedProperty> properties;\n";
    out << "};\n";
    out << "struct AXGeneratedObject {\n";
    out << "    const char* name;\n";
    out << "    const char* type;\n";
    out << "    const char* sourcePath;\n";
    out << "    bool active;\n";
    out << "    bool isStatic;\n";
    out << "    int parentIndex;\n";
    out << "    float position[3];\n";
    out << "    float rotation[3];\n";
    out << "    float scale[3];\n";
    out << "    std::vector<AXGeneratedComponent> components;\n";
    out << "};\n\n";

    out << "std::vector<AXGeneratedObject> buildGeneratedSceneObjects() {\n";
    out << "    std::vector<AXGeneratedObject> objects;\n";

    for (const EditorObject& obj : objects) {
        out << "    {\n";
        out << "        AXGeneratedObject obj{};\n";
        out << "        obj.name = \"" << escapeCpp(obj.name) << "\";\n";
        out << "        obj.type = \"" << escapeCpp(obj.type) << "\";\n";
        out << "        obj.sourcePath = \"" << escapeCpp(obj.sourcePath) << "\";\n";
        out << "        obj.active = " << (obj.active ? "true" : "false") << ";\n";
        out << "        obj.isStatic = " << (obj.isStatic ? "true" : "false") << ";\n";
        out << "        obj.parentIndex = " << obj.parentIndex << ";\n";
        out << "        obj.position[0] = " << cppFloat(obj.position[0]) << "; obj.position[1] = " << cppFloat(obj.position[1]) << "; obj.position[2] = " << cppFloat(obj.position[2]) << ";\n";
        out << "        obj.rotation[0] = " << cppFloat(obj.rotation[0]) << "; obj.rotation[1] = " << cppFloat(obj.rotation[1]) << "; obj.rotation[2] = " << cppFloat(obj.rotation[2]) << ";\n";
        out << "        obj.scale[0] = " << cppFloat(obj.scale[0]) << "; obj.scale[1] = " << cppFloat(obj.scale[1]) << "; obj.scale[2] = " << cppFloat(obj.scale[2]) << ";\n";
        for (const EditorComponent& c : obj.components) {
            out << "        {\n";
            out << "            AXGeneratedComponent c{};\n";
            out << "            c.type = \"" << escapeCpp(c.type) << "\";\n";
            out << "            c.active = " << (c.active ? "true" : "false") << ";\n";
            out << "            c.dynamic = " << (c.dynamic ? "true" : "false") << ";\n";
            for (const EditorProperty& p : c.properties) {
                out << "            c.properties.push_back({\"" << escapeCpp(p.name) << "\", \"" << escapeCpp(p.value) << "\"});\n";
            }
            out << "            obj.components.push_back(c);\n";
            out << "        }\n";
        }
        out << "        objects.push_back(obj);\n";
        out << "    }\n";
    }

    out << "    return objects;\n";
    out << "}\n\n";

    out << "// Component authoring notes:\n";
    out << "// - StaticMeshRenderer / SkinnedMeshRenderer are renderer components.\n";
    out << "// - ProceduralAnimator, SocketBinding and SwordTrail are animation/VFX metadata.\n";
    out << "// - VoxelTerrain and LODGroup are engine-level systems exposed to the editor.\n";
    out << "// - ScriptComponent references user-owned scripts but this generator never overwrites them.\n";
    return true;
}
