#include "AIEditorPanel.h"
#include "PanelLayout.h"
#include "EditorState.h"
#include "EditorPanelUtil.h"
#include <imgui.h>
#include <misc/cpp/imgui_stdlib.h>
#include <sstream>
#include <vector>

namespace { struct AiAttack{std::string name="SingleShot";float range=12,cooldown=1.4f,windup=.35f,damage=12;}; static std::vector<AiAttack> attacks={{"SingleShot",14,1.4f,.35f,12},{"RetreatShot",8,2.0f,.25f,8}}; static int selected=0; static std::string status="Ready"; static bool canStrafe=true, canLaunch=false, armor=false; static float hp=120, stagger=45, moveSpeed=3.2f;
static std::string json(EditorState&s){std::ostringstream o;o<<"{\n  \"type\": \"AXEnemy\",\n  \"version\": 2,\n  \"assetId\": \""<<axed::stableIdFor(s.aiEditorPath)<<"\",\n  \"health\": "<<hp<<",\n  \"moveSpeed\": "<<moveSpeed<<",\n  \"detectionRange\": "<<s.aiDetectionRange<<",\n  \"preferredRange\": "<<s.aiPreferredRange<<",\n  \"attackCooldown\": "<<s.aiAttackCooldown<<",\n  \"canStrafe\": "<<(canStrafe?"true":"false")<<",\n  \"armor\": "<<(armor?"true":"false")<<",\n  \"launchable\": "<<(canLaunch?"true":"false")<<",\n  \"staggerThreshold\": "<<stagger<<",\n  \"states\": [\"Idle\",\"Patrol\",\"Chase\",\"Strafe\",\"Attack\",\"Recover\",\"Stagger\",\"Dead\"],\n  \"attacks\": [\n";for(size_t i=0;i<attacks.size();++i){auto&a=attacks[i];o<<"    { \"name\": \""<<axed::escapeJson(a.name)<<"\", \"range\": "<<a.range<<", \"cooldown\": "<<a.cooldown<<", \"windup\": "<<a.windup<<", \"damage\": "<<a.damage<<" }"<<(i+1<attacks.size()?",":"")<<"\n";}o<<"  ]\n}\n";return o.str();}
static void load(EditorState&s){std::string t,err;if(!axed::readTextFile(axed::resolvePath(s,s.aiEditorPath),t,&err)){status=err+" - using editable defaults.";return;}hp=axed::getFloat(t,"health",hp);moveSpeed=axed::getFloat(t,"moveSpeed",moveSpeed);s.aiDetectionRange=axed::getFloat(t,"detectionRange",s.aiDetectionRange);s.aiPreferredRange=axed::getFloat(t,"preferredRange",s.aiPreferredRange);s.aiAttackCooldown=axed::getFloat(t,"attackCooldown",s.aiAttackCooldown);armor=axed::getBool(t,"armor",armor);canLaunch=axed::getBool(t,"launchable",canLaunch);status="Loaded "+s.aiEditorPath;}
static void save(EditorState&s){std::string err;if(axed::writeTextFile(axed::resolvePath(s,s.aiEditorPath),json(s),&err)){status="Saved "+s.aiEditorPath;s.log(status);}else{status=err;s.log(err);}}
}
void drawAIEditorPanel(EditorState& state){AXEditorLayout::prepareFloatingTool(state, 760.0f, 620.0f); if(!ImGui::Begin("AI Editor",&state.showAIEditor)){ImGui::End();return;} ImGui::InputText("Enemy file",&state.aiEditorPath); if(ImGui::Button("Load"))load(state); ImGui::SameLine(); if(ImGui::Button("Save"))save(state); ImGui::SameLine(); if(ImGui::Button("+ Attack")){attacks.push_back({"NewAttack",10,1,.2f,10});selected=(int)attacks.size()-1;} ImGui::TextDisabled("%s",status.c_str()); ImGui::Columns(2,"aicols",true); ImGui::Text("Enemy Stats"); ImGui::DragFloat("HP",&hp,1,1,9999); ImGui::DragFloat("Move speed",&moveSpeed,.1f,0,50); ImGui::DragFloat("Detection range",&state.aiDetectionRange,.1f,0,200); ImGui::DragFloat("Preferred range",&state.aiPreferredRange,.1f,0,200); ImGui::DragFloat("Global cooldown",&state.aiAttackCooldown,.05f,0,30); ImGui::DragFloat("Stagger threshold",&stagger,1,0,999); ImGui::Checkbox("Can strafe",&canStrafe); ImGui::SameLine(); ImGui::Checkbox("Armor",&armor); ImGui::SameLine(); ImGui::Checkbox("Launchable",&canLaunch); ImGui::Separator(); ImGui::Text("State machine"); const char* states[]={"Idle","Patrol","Chase","Strafe","Attack","Recover","Stagger","Dead"}; for(auto*s:states) ImGui::BulletText("%s",s); ImGui::NextColumn(); ImGui::Text("Attacks"); for(size_t i=0;i<attacks.size();++i){if(ImGui::Selectable(attacks[i].name.c_str(),selected==(int)i))selected=(int)i;} if(selected>=0&&selected<(int)attacks.size()){auto&a=attacks[selected];ImGui::Separator();ImGui::InputText("Name",&a.name);ImGui::DragFloat("Range",&a.range,.1f,0,200);ImGui::DragFloat("Cooldown",&a.cooldown,.05f,0,30);ImGui::DragFloat("Windup",&a.windup,.01f,0,10);ImGui::DragFloat("Damage",&a.damage,1,0,999); if(ImGui::Button("Delete Attack")&&attacks.size()>1){attacks.erase(attacks.begin()+selected);selected=0;}} std::string src=json(state); ImGui::InputTextMultiline("Generated .axenemy",&src,ImVec2(-1,210),ImGuiInputTextFlags_ReadOnly); ImGui::Columns(1); ImGui::End();}
