#include "AnimationTimelinePanel.h"
#include "PanelLayout.h"
#include "EditorState.h"
#include "EditorPanelUtil.h"
#include <imgui.h>
#include <misc/cpp/imgui_stdlib.h>
#include <sstream>
#include <vector>
#include <algorithm>

namespace { struct Event{std::string track="Attack";std::string name="HitboxOn";float time=.2f;std::string value="MainSlash";}; static std::vector<Event> events={{"Attack","HitboxOn",.18f,"MainSlash"},{"VFX","Spawn",.14f,"Slash_WideArc"},{"Audio","Play",.12f,"swing"},{"Cancel","Open",.34f,"SwordAttack2"}}; static int selected=0; static std::string path="assets/animations/Attack_01.axtimeline"; static std::string status="Ready"; static bool play=false; static float speed=1.0f;
static std::string json(EditorState&s){std::ostringstream o;o<<"{\n  \"type\": \"AXAnimationTimeline\",\n  \"version\": 2,\n  \"assetId\": \""<<axed::stableIdFor(path)<<"\",\n  \"clip\": \""<<axed::escapeJson(s.animationTimelineClip)<<"\",\n  \"fps\": "<<s.animationTimelineFps<<",\n  \"duration\": "<<s.animationTimelineDuration<<",\n  \"loop\": "<<(s.animationTimelineLoop?"true":"false")<<",\n  \"events\": [\n";for(size_t i=0;i<events.size();++i){auto&e=events[i];o<<"    { \"track\": \""<<axed::escapeJson(e.track)<<"\", \"time\": "<<e.time<<", \"name\": \""<<axed::escapeJson(e.name)<<"\", \"value\": \""<<axed::escapeJson(e.value)<<"\" }"<<(i+1<events.size()?",":"")<<"\n";}o<<"  ]\n}\n";return o.str();}
static void load(EditorState&s){std::string t,err;if(!axed::readTextFile(axed::resolvePath(s,path),t,&err)){status=err+" - using current timeline.";return;}s.animationTimelineClip=axed::getString(t,"clip",s.animationTimelineClip);s.animationTimelineFps=axed::getFloat(t,"fps",s.animationTimelineFps);s.animationTimelineDuration=axed::getFloat(t,"duration",s.animationTimelineDuration);s.animationTimelineLoop=axed::getBool(t,"loop",s.animationTimelineLoop);status="Loaded "+path;}
static void save(EditorState&s){std::string err;if(axed::writeTextFile(axed::resolvePath(s,path),json(s),&err)){status="Saved "+path;s.log(status);}else{status=err;s.log(err);}}
}
void drawAnimationTimelinePanel(EditorState& state){AXEditorLayout::prepareFloatingTool(state, 900.0f, 560.0f); if(!ImGui::Begin("Animation Timeline",&state.showAnimationTimeline)){ImGui::End();return;} ImGui::TextWrapped("Gameplay timeline for Blender-exported clips. AXEngine does not create keyframes; it authors events over seconds/frames."); ImGui::InputText("Timeline asset",&path); if(ImGui::Button("Load"))load(state); ImGui::SameLine(); if(ImGui::Button("Save"))save(state); ImGui::SameLine(); if(ImGui::Button(play?"Pause":"Play"))play=!play; ImGui::SameLine(); if(ImGui::Button("+ Event")){events.push_back({"Attack","NewEvent",state.animationTimelineScrub,""});selected=(int)events.size()-1;} ImGui::TextDisabled("%s",status.c_str()); ImGui::InputText("Clip",&state.animationTimelineClip); ImGui::DragFloat("FPS",&state.animationTimelineFps,1,1,240); ImGui::SameLine(); ImGui::DragFloat("Duration",&state.animationTimelineDuration,.01f,.01f,120,"%.2fs"); ImGui::SameLine(); ImGui::DragFloat("Speed",&speed,.05f,.05f,4); ImGui::Checkbox("Loop",&state.animationTimelineLoop); if(play){state.animationTimelineScrub+=ImGui::GetIO().DeltaTime*speed; if(state.animationTimelineScrub>state.animationTimelineDuration) state.animationTimelineScrub=state.animationTimelineLoop?0:state.animationTimelineDuration;} state.animationTimelineScrub=std::clamp(state.animationTimelineScrub,0.0f,state.animationTimelineDuration); ImGui::SliderFloat("Time",&state.animationTimelineScrub,0,state.animationTimelineDuration,"%.3fs"); int frame=(int)(state.animationTimelineScrub*state.animationTimelineFps+.5f), total=(int)(state.animationTimelineDuration*state.animationTimelineFps+.5f); ImGui::Text("Frame: %d / %d",frame,total);
 ImVec2 p=ImGui::GetCursorScreenPos(); float w=ImGui::GetContentRegionAvail().x; float h=160; ImGui::InvisibleButton("timeline",ImVec2(w,h)); ImDrawList*dl=ImGui::GetWindowDrawList(); dl->AddRectFilled(p,ImVec2(p.x+w,p.y+h),IM_COL32(25,27,33,255)); const char* tracks[]={"Attack","VFX","Audio","Cancel"}; for(int r=0;r<4;r++){float y=p.y+24+r*30; dl->AddText(ImVec2(p.x+8,y-10),IM_COL32(180,190,210,255),tracks[r]); dl->AddLine(ImVec2(p.x+85,y),ImVec2(p.x+w-8,y),IM_COL32(70,75,86,255));} for(int i=0;i<=10;i++){float x=p.x+90+(w-110)*i/10.0f; dl->AddLine(ImVec2(x,p.y),ImVec2(x,p.y+h),IM_COL32(55,60,68,255));} for(size_t i=0;i<events.size();++i){int row=0;for(int r=0;r<4;r++)if(events[i].track==tracks[r])row=r; float x=p.x+90+(w-110)*std::clamp(events[i].time/state.animationTimelineDuration,0.0f,1.0f); float y=p.y+24+row*30; ImU32 col=(i==(size_t)selected)?IM_COL32(255,200,80,255):IM_COL32(90,190,255,255); dl->AddCircleFilled(ImVec2(x,y),6,col); dl->AddText(ImVec2(x+8,y-8),col,events[i].name.c_str());} float sx=p.x+90+(w-110)*(state.animationTimelineScrub/std::max(.001f,state.animationTimelineDuration)); dl->AddLine(ImVec2(sx,p.y),ImVec2(sx,p.y+h),IM_COL32(255,80,80,255),2);
 ImGui::Columns(2,"evcols",true); if(ImGui::BeginChild("events",ImVec2(0,220),true)){for(size_t i=0;i<events.size();++i){std::string lab=events[i].track+" @ "+std::to_string(events[i].time)+"  "+events[i].name; if(ImGui::Selectable(lab.c_str(),selected==(int)i))selected=(int)i;}}ImGui::EndChild(); ImGui::NextColumn(); if(selected>=0&&selected<(int)events.size()){auto&e=events[selected]; ImGui::InputText("Track",&e.track); ImGui::InputText("Name",&e.name); ImGui::DragFloat("Time",&e.time,.01f,0,state.animationTimelineDuration); ImGui::InputText("Value",&e.value); if(ImGui::Button("Delete")&&events.size()>1){events.erase(events.begin()+selected);selected=0;} ImGui::SameLine(); if(ImGui::Button("Sort"))std::sort(events.begin(),events.end(),[](auto&a,auto&b){return a.time<b.time;});} ImGui::Columns(1); ImGui::End();}
