#include "AssetRegistryPanel.h"
#include "PanelLayout.h"
#include "EditorState.h"
#include "EditorPanelUtil.h"
#include <imgui.h>
#include <misc/cpp/imgui_stdlib.h>
#include <sstream>
#include <vector>

namespace{struct Row{std::string type,path,id;int version=1;};static std::vector<Row> rows;static std::string filter;static std::string status="Not scanned";static std::string regPath="assets/AXAssetRegistry.axregistry";static std::string typeFor(const std::filesystem::path&p){auto e=axed::lower(p.extension().string());if(e==".axscene")return"AXScene";if(e==".axmat")return"AXMaterial";if(e==".axattack")return"AXAttack";if(e==".axvfx")return"AXVFX";if(e==".axinput")return"AXInput";if(e==".axenemy")return"AXEnemy";if(e==".axui")return"AXUI";if(e==".glb")return"GLB";if(e==".vert"||e==".frag")return"Shader";return"Asset";}static void scan(EditorState&s){rows.clear();auto files=axed::scanFiles(s,{".axscene",".axmat",".axattack",".axvfx",".axinput",".axenemy",".axui",".axrender",".glb",".vert",".frag",".png",".jpg",".wav",".ogg"});for(auto&f:files){auto rel=axed::relativePath(s,f);rows.push_back({typeFor(f),rel,axed::stableIdFor(rel),1});}status="Scanned "+std::to_string(rows.size())+" assets";}static std::string json(){std::ostringstream o;o<<"{\n  \"type\": \"AXAssetRegistry\",\n  \"version\": 1,\n  \"assets\": [\n";for(size_t i=0;i<rows.size();++i){auto&r=rows[i];o<<"    { \"type\": \""<<r.type<<"\", \"path\": \""<<axed::escapeJson(r.path)<<"\", \"assetId\": \""<<r.id<<"\", \"version\": "<<r.version<<" }"<<(i+1<rows.size()?",":"")<<"\n";}o<<"  ]\n}\n";return o.str();}static void save(EditorState&s){std::string err;if(axed::writeTextFile(axed::resolvePath(s,regPath),json(),&err)){status="Saved "+regPath;s.log(status);}else{status=err;s.log(err);}}}
void drawAssetRegistryPanel(EditorState& state){AXEditorLayout::prepareFloatingTool(state, 820.0f, 600.0f); if(!ImGui::Begin("Asset Registry / Versioning",&state.showAssetRegistry)){ImGui::End();return;} ImGui::InputText("Registry file",&regPath); if(ImGui::Button("Scan Project"))scan(state); ImGui::SameLine(); if(ImGui::Button("Save Registry")){if(rows.empty())scan(state); save(state);} ImGui::SameLine(); if(ImGui::Button("Open Registry")) axed::openInOs(axed::resolvePath(state,regPath)); ImGui::TextDisabled("%s",status.c_str()); ImGui::InputTextWithHint("Filter","scene, attack, glb, shader...",&filter); if(ImGui::BeginTable("assettable",4,ImGuiTableFlags_RowBg|ImGuiTableFlags_Borders|ImGuiTableFlags_Resizable|ImGuiTableFlags_ScrollY,ImVec2(0,430))){ImGui::TableSetupColumn("Type");ImGui::TableSetupColumn("Path");ImGui::TableSetupColumn("Stable ID");ImGui::TableSetupColumn("Version");ImGui::TableHeadersRow();for(auto&r:rows){std::string all=r.type+" "+r.path+" "+r.id;if(!filter.empty()&&!axed::containsNoCase(all,filter))continue;ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(r.type.c_str());ImGui::TableNextColumn();if(ImGui::Selectable(r.path.c_str(),false,ImGuiSelectableFlags_SpanAllColumns)){}if(ImGui::IsItemHovered()&&ImGui::IsMouseDoubleClicked(0))axed::openInOs(axed::resolvePath(state,r.path));ImGui::TableNextColumn();ImGui::TextUnformatted(r.id.c_str());ImGui::TableNextColumn();ImGui::Text("%d",r.version);}ImGui::EndTable();} ImGui::End();}
