#include "DebugProfilerPanel.h"
#include "PanelLayout.h"
#include "EditorState.h"
#include "EditorPanelUtil.h"
#include <imgui.h>
#include <misc/cpp/imgui_stdlib.h>
#include <sstream>

namespace {static float cpu=6.9f,gpu=5.2f,ai=0.7f,anim=1.1f,vfx=0.4f,coll=0.3f;static bool writeConfig=true;static std::string path="assets/debug/RuntimeDebug.axdebug";static std::string status="Ready";static std::string json(EditorState&s){std::ostringstream o;o<<"{\n  \"type\": \"AXDebugConfig\",\n  \"version\": 1,\n  \"showAttackVolumes\": "<<(s.debugShowColliders?"true":"false")<<",\n  \"showHurtboxes\": "<<(s.debugShowHurtboxes?"true":"false")<<",\n  \"showInputBuffer\": "<<(s.debugShowInputBuffer?"true":"false")<<",\n  \"showAiState\": "<<(s.debugShowAiState?"true":"false")<<",\n  \"showProfiler\": "<<(s.debugShowFrameProfiler?"true":"false")<<"\n}\n";return o.str();}static void save(EditorState&s){std::string err;if(axed::writeTextFile(axed::resolvePath(s,path),json(s),&err)){status="Saved "+path;s.log(status);}else{status=err;s.log(err);}}}
void drawDebugProfilerPanel(EditorState& state){AXEditorLayout::prepareFloatingTool(state, 660.0f, 560.0f); if(!ImGui::Begin("Debug / Profiler",&state.showDebugProfiler)){ImGui::End();return;} ImGui::TextWrapped("Debug configuration and live-style profiler mockup. Runtime can read this to decide which overlays to draw."); ImGui::InputText("Debug config",&path); if(ImGui::Button("Save Debug Config"))save(state); ImGui::SameLine(); ImGui::Checkbox("Write config",&writeConfig); ImGui::TextDisabled("%s",status.c_str()); ImGui::Columns(2,"dbgcols",true); ImGui::Checkbox("Attack volumes",&state.debugShowColliders); ImGui::Checkbox("Enemy hurtboxes",&state.debugShowHurtboxes); ImGui::Checkbox("Input buffer",&state.debugShowInputBuffer); ImGui::Checkbox("AI labels",&state.debugShowAiState); ImGui::Checkbox("Frame profiler",&state.debugShowFrameProfiler); ImGui::Separator(); ImGui::Text("Overlay groups"); ImGui::BulletText("Scene: loaded .axscene, root scale, GLB path"); ImGui::BulletText("Render: draw calls, material/bloom identity"); ImGui::BulletText("Combat: attack volume, hit memory, hitstop"); ImGui::BulletText("AI: state, target, cooldown, stagger"); ImGui::NextColumn(); ImGui::Text("Frame budget"); auto bar=[](const char*n,float v){ImGui::ProgressBar(std::min(v/16.6f,1.0f),ImVec2(-1,0),(std::string(n)+" "+std::to_string(v).substr(0,4)+"ms").c_str());}; bar("CPU",cpu);bar("GPU",gpu);bar("Animation",anim);bar("AI",ai);bar("VFX",vfx);bar("Collision",coll); ImGui::DragFloat("CPU sim",&cpu,.1f,0,40); ImGui::DragFloat("GPU sim",&gpu,.1f,0,40); ImGui::Separator(); std::string src=json(state); ImGui::InputTextMultiline("Generated .axdebug",&src,ImVec2(-1,160),ImGuiInputTextFlags_ReadOnly); ImGui::Columns(1); ImGui::End();}
