#include "GameUIPanel.h"
#include "PanelLayout.h"
#include "EditorState.h"
#include "EditorPanelUtil.h"
#include <imgui.h>
#include <misc/cpp/imgui_stdlib.h>
#include <sstream>
#include <vector>

namespace{struct UiEl{std::string name="Health";std::string type="Bar";float x=.03f,y=.04f,w=.25f,h=.035f;float color[4]={.8f,.1f,.1f,1};};static std::vector<UiEl> els={{"Health","Bar",.03f,.04f,.25f,.035f,{.8f,.1f,.1f,1}},{"StyleRank","Text",.82f,.04f,.12f,.05f,{1,.85f,.1f,1}},{"LockOn","Reticle",.48f,.48f,.04f,.07f,{1,1,1,1}}};static int sel=0;static std::string status="Ready";static std::string json(EditorState&s){std::ostringstream o;o<<"{\n  \"type\": \"AXUI\",\n  \"version\": 2,\n  \"assetId\": \""<<axed::stableIdFor(s.gameUiPath)<<"\",\n  \"elements\": [\n";for(size_t i=0;i<els.size();++i){auto&e=els[i];o<<"    { \"name\": \""<<axed::escapeJson(e.name)<<"\", \"kind\": \""<<axed::escapeJson(e.type)<<"\", \"rect\": ["<<e.x<<", "<<e.y<<", "<<e.w<<", "<<e.h<<"], \"color\": ["<<e.color[0]<<", "<<e.color[1]<<", "<<e.color[2]<<", "<<e.color[3]<<"] }"<<(i+1<els.size()?",":"")<<"\n";}o<<"  ]\n}\n";return o.str();}static void save(EditorState&s){std::string err;if(axed::writeTextFile(axed::resolvePath(s,s.gameUiPath),json(s),&err)){status="Saved "+s.gameUiPath;s.log(status);}else{status=err;s.log(err);}}static void load(EditorState&s){std::string t,err;if(axed::readTextFile(axed::resolvePath(s,s.gameUiPath),t,&err))status="Loaded "+s.gameUiPath;else status=err+" - using editable HUD.";}}
void drawGameUIPanel(EditorState& state){AXEditorLayout::prepareFloatingTool(state, 760.0f, 560.0f); if(!ImGui::Begin("Game UI Editor",&state.showGameUIEditor)){ImGui::End();return;} ImGui::InputText("UI file",&state.gameUiPath); if(ImGui::Button("Load"))load(state); ImGui::SameLine(); if(ImGui::Button("Save"))save(state); ImGui::SameLine(); if(ImGui::Button("+ Element")){els.push_back({"NewElement","Text",.45f,.45f,.12f,.04f,{1,1,1,1}});sel=(int)els.size()-1;} ImGui::TextDisabled("%s",status.c_str()); ImGui::Columns(2,"uicols",true); ImVec2 p=ImGui::GetCursorScreenPos(); ImVec2 sz(ImGui::GetContentRegionAvail().x,320); ImGui::InvisibleButton("hudpreview",sz); ImDrawList*dl=ImGui::GetWindowDrawList(); dl->AddRectFilled(p,ImVec2(p.x+sz.x,p.y+sz.y),IM_COL32(18,20,24,255)); dl->AddText(ImVec2(p.x+8,p.y+8),IM_COL32(120,130,145,255),"HUD Preview"); for(size_t i=0;i<els.size();++i){auto&e=els[i]; ImVec2 a(p.x+e.x*sz.x,p.y+e.y*sz.y), b(a.x+e.w*sz.x,a.y+e.h*sz.y); ImU32 c=ImGui::ColorConvertFloat4ToU32(ImVec4(e.color[0],e.color[1],e.color[2],e.color[3])); if(e.type=="Bar") dl->AddRectFilled(a,b,c,3); else if(e.type=="Reticle"){ImVec2 cc((a.x+b.x)/2,(a.y+b.y)/2); dl->AddCircle(cc,std::max(e.w*sz.x,e.h*sz.y)*.5f,c,32,2);} else dl->AddText(a,c,e.name.c_str()); if((int)i==sel) dl->AddRect(a,b,IM_COL32(255,210,80,255),2.0f,2.0f,0);} ImGui::NextColumn(); for(size_t i=0;i<els.size();++i) if(ImGui::Selectable(els[i].name.c_str(),sel==(int)i))sel=(int)i; if(sel>=0&&sel<(int)els.size()){auto&e=els[sel];ImGui::Separator();ImGui::InputText("Name",&e.name);ImGui::InputText("Type",&e.type);ImGui::DragFloat2("Pos",&e.x,.005f,0,1);ImGui::DragFloat2("Size",&e.w,.005f,.001f,1);ImGui::ColorEdit4("Color",e.color); if(ImGui::Button("Delete")&&els.size()>1){els.erase(els.begin()+sel);sel=0;}} std::string src=json(state); ImGui::InputTextMultiline("Generated .axui",&src,ImVec2(-1,160),ImGuiInputTextFlags_ReadOnly); ImGui::Columns(1); ImGui::End();}
