#include "InputMapPanel.h"
#include "PanelLayout.h"
#include "EditorState.h"
#include "EditorPanelUtil.h"
#include <imgui.h>
#include <misc/cpp/imgui_stdlib.h>
#include <sstream>
#include <vector>

namespace { struct Binding{std::string action, keyboard, gamepad; bool buffer=true; float hold=0.0f;}; static std::vector<Binding> g={{"Move","WASD","LeftStick",false,0},{"CameraLook","Mouse","RightStick",false,0},{"Attack","MouseLeft","X",true,0},{"Special","MouseRight","Y",true,0},{"Jump","Space","A",true,0},{"Dash","E","B",true,0},{"LockOn","Q","RB",true,0},{"SwitchTargetLeft","Z","DPadLeft",true,0},{"SwitchTargetRight","C","DPadRight",true,0}}; static int sel=0; static std::string status="Ready"; static std::string filter;
static std::string json(EditorState&s){std::ostringstream o;o<<"{\n  \"type\": \"AXInputMap\",\n  \"version\": 2,\n  \"assetId\": \""<<axed::stableIdFor(s.inputMapPath)<<"\",\n  \"bufferEnabled\": "<<(s.inputBufferEnabled?"true":"false")<<",\n  \"bufferSeconds\": "<<s.inputBufferSeconds<<",\n  \"controllerEnabled\": "<<(s.inputControllerEnabled?"true":"false")<<",\n  \"bindings\": [\n"; for(size_t i=0;i<g.size();++i){auto&b=g[i];o<<"    { \"action\": \""<<axed::escapeJson(b.action)<<"\", \"keyboard\": \""<<axed::escapeJson(b.keyboard)<<"\", \"gamepad\": \""<<axed::escapeJson(b.gamepad)<<"\", \"buffer\": "<<(b.buffer?"true":"false")<<", \"holdSeconds\": "<<b.hold<<" }"<<(i+1<g.size()?",":"")<<"\n";}o<<"  ]\n}\n";return o.str();}
static void load(EditorState&s){std::string t,err;if(!axed::readTextFile(axed::resolvePath(s,s.inputMapPath),t,&err)){status=err+" - using editable defaults.";return;}s.inputBufferEnabled=axed::getBool(t,"bufferEnabled",s.inputBufferEnabled);s.inputBufferSeconds=axed::getFloat(t,"bufferSeconds",s.inputBufferSeconds);s.inputControllerEnabled=axed::getBool(t,"controllerEnabled",s.inputControllerEnabled);status="Loaded "+s.inputMapPath;}
static void save(EditorState&s){std::string err;if(axed::writeTextFile(axed::resolvePath(s,s.inputMapPath),json(s),&err)){status="Saved "+s.inputMapPath;s.log(status);}else{status=err;s.log(err);}}
}
void drawInputMapPanel(EditorState& state){AXEditorLayout::prepareFloatingTool(state, 820.0f, 620.0f); if(!ImGui::Begin("Input Map Editor",&state.showInputMapEditor)){ImGui::End();return;} ImGui::InputText("Input map",&state.inputMapPath); if(ImGui::Button("Load"))load(state); ImGui::SameLine(); if(ImGui::Button("Save"))save(state); ImGui::SameLine(); if(ImGui::Button("+ Binding")){g.push_back({"NewAction","","",true,0});sel=(int)g.size()-1;} ImGui::TextDisabled("%s",status.c_str()); ImGui::Checkbox("Input buffering",&state.inputBufferEnabled); ImGui::SameLine(); ImGui::DragFloat("Buffer seconds",&state.inputBufferSeconds,0.01f,0,1); ImGui::SameLine(); ImGui::Checkbox("Controller",&state.inputControllerEnabled); ImGui::InputTextWithHint("Filter","attack, dash, keyboard...",&filter); ImGui::Columns(2,"inputcols",true); if(ImGui::BeginChild("bindlist",ImVec2(0,420),true)){for(size_t i=0;i<g.size();++i){auto&b=g[i];std::string label=b.action+"  ["+b.keyboard+" / "+b.gamepad+"]"; if(!filter.empty()&&!axed::containsNoCase(label,filter))continue; if(ImGui::Selectable(label.c_str(),sel==(int)i))sel=(int)i;}}ImGui::EndChild(); ImGui::NextColumn(); if(sel>=0&&sel<(int)g.size()){auto&b=g[sel];ImGui::Text("Binding Details"); ImGui::InputText("Action",&b.action); ImGui::InputText("Keyboard",&b.keyboard); ImGui::InputText("Gamepad",&b.gamepad); ImGui::Checkbox("Buffer this action",&b.buffer); ImGui::DragFloat("Hold threshold",&b.hold,0.01f,0,3,"%.2fs"); if(ImGui::Button("Duplicate")){g.push_back(b);sel=(int)g.size()-1;} ImGui::SameLine(); if(ImGui::Button("Delete")&&g.size()>1){g.erase(g.begin()+sel);sel=std::min(sel,(int)g.size()-1);} ImGui::Separator(); ImGui::TextWrapped("Runtime use: query by action name, not raw key. This enables keyboard/gamepad rebinding and combo input buffering.");}
 std::string src=json(state); ImGui::InputTextMultiline("Generated .axinput",&src,ImVec2(-1,190),ImGuiInputTextFlags_ReadOnly); ImGui::Columns(1); ImGui::End();}
